%% setting up the GUI
gui = StandardGUI(sim, [50, 50, 1000, 720], 0.01, [0.1, 0.1, 0.8, 0.9], [3, 1], 0.08, [0.0, 0.0, 1.0, 0.05], [1, 6], ...
  elementGroups, elementsInGroup);

gui.addVisualization(SurfacePlot('history trial', 'output', [-15, 15], 'mesh', {'view', [-10,30],'fontsize',20}, ...
    {}, 'field activation', ...
  'feature space', '', 'activation'), [1, 1]);

gui.addVisualization(MultiPlot({'field u', 'field u', 'mem u'}, {'activation', 'output', 'output'}, ...
  [1, 10, 10], 'horizontal', {'YLim', [-15, 15], 'XGrid', 'on', 'YGrid', 'on','fontsize', 20}, ...
  {{'b', 'LineWidth', 3}, {'r', 'LineWidth', 2}, ...
  {'Color', 'c', 'LineWidth', 2} }, ...
  'field activation - final time step', ...
  'feature space', 'activation / output'), [2, 1]);

gui.addVisualization(KernelPlot({'u -> u', 'u -> u'}, {'kernel', 'amplitudeGlobal'}, ...
  {'local', 'global'}, fieldSize/2, {'YLim', [-0.5, 1.5], 'XGrid', 'on', 'YGrid', 'on', 'fontsize', 20}, ...
  {'Color', [0.5, 0, 0], 'LineWidth', 2}, ...
  'interaction function', 'distance in feature space', 'interaction weight'), [3, 1]);

% % % add buttons
gui.addControl(GlobalControlButton('Pause', gui, 'pauseSimulation', true, false, false, 'pause simulation'), [1, 1]);
gui.addControl(GlobalControlButton('Reset', gui, 'resetSimulation', true, false, true, 'reset simulation'), [1, 2]);
gui.addControl(GlobalControlButton('Parameters', gui, 'paramPanelRequest', true, false, false, 'open parameter panel'), [1, 3]);
gui.addControl(GlobalControlButton('Save', gui, 'saveParameters', true, false, true, 'save parameter settings'), [1, 4]);
gui.addControl(GlobalControlButton('Load', gui, 'loadParameters', true, false, true, 'load parameter settings'), [1, 5]);
gui.addControl(GlobalControlButton('Quit', gui, 'quitSimulation', true, false, false, 'quit simulation'), [1, 6]);

