%% create controls
% sliders for boosts
%gui.addControl(ParameterSlider('atn_sa', 'boost atn_sa', 'amplitude', [-5, 5], '%0.1f', 1, 'boost atn_sa'), [1, 1]);
%gui.addControl(ParameterSlider('con_s', 'boost con_s', 'amplitude', [-5, 5], '%0.1f', 1, 'boost con_s'), [2, 1]);
%gui.addControl(ParameterSlider('wm_s', 'boost wm_s', 'amplitude', [-5, 5], '%0.1f', 1, 'boost wm_s'), [3, 1]);
%gui.addControl(ParameterSlider('atn_c', 'boost atn_c', 'amplitude', [-5, 5], '%0.1f', 1, 'boost atn_c'), [4, 1]);
%gui.addControl(ParameterSlider('atn_c2', 'boost atn_c2', 'amplitude', [-5, 5], '%0.1f', 1, 'boost atn_c2'), [4, 1]);
%gui.addControl(ParameterSlider('wm_c', 'boost wm_c', 'amplitude', [-5, 5], '%0.1f', 1, 'boost wm_c'), [5, 1]);

%gui.addControl(ParameterSlider('ior_s', 'boost ior_s', 'amplitude', [-5, 5], '%0.1f', 1, 'boost ior_s'), [1, 2]);
%gui.addControl(ParameterSlider('atn_sr', 'boost atn_sr', 'amplitude', [-5, 5], '%0.1f', 1, 'boost atn_sr'), [2, 2]);
%gui.addControl(ParameterSlider('atn_f', 'boost atn_f', 'amplitude', [-5, 5], '%0.1f', 1, 'boost atn_f'), [3, 2]);
%gui.addControl(ParameterSlider('con_f', 'boost con_f', 'amplitude', [-5, 5], '%0.1f', 1, 'boost con_f'), [4, 2]);
%gui.addControl(ParameterSlider('wm_f', 'boost wm_f', 'amplitude', [-5, 5], '%0.1f', 1, 'boost wm_f'), [5, 2]);
% gui.addControl(ParameterSwitchButton('Coupling on/off', ...
%   {'scale atn_sr -> atn_sa', 'scale atn_sa -> atn_sr', 'scale ior_s -> atn_sa', 'atn_sa', 'mrn' ...
%   'atn_c1 -> wm_c1', 'atn_c2 -> wm_c2', ...
%   'atn_c1 -> wm_c1 (inh.)', 'atn_c2 -> wm_c2 (inh.)', 'con_f1', 'con_f2'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'h', 'h', ...
%   'amplitude', 'amplitude', 'amplitude', 'amplitude', 'h', 'h'}, ...
%   [0.0, 0.0, 0.0, -3, 0, 0, 0, 0, 0, -5, -5], [1.0, 1.0, 1.0, -5, -5, 10, 10, -75, -75, -5, -5], ...
%   'coupling between retinal and allocentric spatial attention', false), [6, 5]);
% 
% gui.addControl(ParameterSwitchButton('Coupling weak/on', ...
%   {'scale atn_sr -> atn_sa', 'scale atn_sa -> atn_sr', 'scale ior_s -> atn_sa',...
%   'atn_sa', 'mrn', 'atn_c1 -> wm_c1', 'atn_c2 -> wm_c2', ...
%   'atn_c1 -> wm_c1 (inh.)', 'atn_c2 -> wm_c2 (inh.)'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'h', 'h',  ...
%   'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   [1.0, 1.0, 1.0, -5, -5, 10, 10, -50, -50], [0.28, 0.28, 0.0, -3, 0, 0, 0, 0, 0], ...
%   'coupling between retinal and allocentric spatial attention', false), [5, 5]);

%gui.addControl(ParameterSwitchButton('Color Priming', {'inputColor', ...
%    'atn_c1 -> hatn_c1'}, {'amplitude', 'amplitude'}, [0, 5.5], [7,1], [], false), [1,5]);
%gui.addControl(ParameterSwitchButton('Shape Priming', {'inputShape', ...
%    'atn_c2 -> hatn_c2'}, {'amplitude', 'amplitude'}, [0, 5.5], [7,1], [], false), [2,5]);
%gui.addControl(ParameterSwitchButton('"Color"', 'inputColor', 'amplitude', 0, 8), [2,5]);
%gui.addControl(ParameterSwitchButton('"Shape"', 'inputShape', 'amplitude', 0, 8), [3,5]);


% % gui.addControl(ParameterSwitchButton('WB Target B', ...
% %   {'input 1Bl', 'input 2Bl'}, ...
% %   {'amplitude', 'amplitude'}, zeros(1, 2), vstrength * ones(1, 2), [], false), [1, 1]);
% % gui.addControl(ParameterSwitchButton('WB Target E', ...
% %   {'input 1Er', 'input 2Er'}, ...
% %   {'amplitude', 'amplitude'}, zeros(1, 2), vstrength * ones(1, 2), [], false), [2, 1]);
% % gui.addControl(ParameterSwitchButton('WB Word/Point L', ...
% %   {'inputColor', 'inputSpacel'}, ...
% %   {'amplitude', 'amplitude'}, zeros(1, 2), wstrength * ones(1, 2), [], false), [3, 1]);
% % gui.addControl(ParameterSwitchButton('WB Word/Point R', ...
% %   {'inputColor', 'inputSpacer'}, ...
% %   {'amplitude', 'amplitude'}, zeros(1, 2), wstrength * ones(1, 2), [], false), [4, 1]);
% % gui.addControl(ParameterSwitchButton('WB Test', ...
% %   {'inputColor', 'input 1Bm', 'input 1Em', 'input 2Bm', 'input 2Em'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude', 'amplitude'}, zeros(1, 5), [wstrength,vstrength,vstrength,vstrength,vstrength], [], false), [5, 1]);
% % gui.addControl(ParameterSwitchButton('Dax Test', ...
% %   {'inputShape', 'input 1Bl', 'input 1El', 'input 2Br', 'input 2Er'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude', 'amplitude'}, zeros(1, 5), [wstrength,vstrength,vstrength,vstrength,vstrength], [], false), [6, 1]);


% gui.addControl(ParameterSwitchButton('Xsit AD', ...
%   {'input 1Al', 'input 1Dr', 'input 2Al', 'input 2Dr'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [1, 2]);
% gui.addControl(ParameterSwitchButton('Xsit BE', ...
%   {'input 1Bl', 'input 1Er', 'input 2Bl', 'input 2Er'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [2, 2]);
% gui.addControl(ParameterSwitchButton('Xsit CF', ...
%   {'input 1Cl', 'input 1Fr', 'input 2Cl', 'input 2Fr'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [3, 2]);
% gui.addControl(ParameterSwitchButton('Xsit FA', ...
%   {'input 1Ar', 'input 1Fl', 'input 2Ar', 'input 2Fl'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [4, 2]);
% gui.addControl(ParameterSwitchButton('Xsit DB', ...
%   {'input 1Br', 'input 1Dl', 'input 2Br', 'input 2Dl'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [5, 2]);
% gui.addControl(ParameterSwitchButton('Xsit EC', ...
%   {'input 1Cr', 'input 1El', 'input 2Cr', 'input 2El'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [6, 2]);
% 
% gui.addControl(ParameterSwitchButton('Xsit AE', ...
%   {'input 1Al', 'input 1Er', 'input 2Al', 'input 2Er'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [1, 3]);
% gui.addControl(ParameterSwitchButton('Xsit CB', ...
%   {'input 1Cl', 'input 1Br', 'input 2Cl', 'input 2Br'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [2, 3]);
% gui.addControl(ParameterSwitchButton('Xsit DC', ...
%   {'input 1Dl', 'input 1Cr', 'input 2Dl', 'input 2Cr'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [3, 3]);
% gui.addControl(ParameterSwitchButton('Xsit BA', ...
%   {'input 1Bl', 'input 1Ar', 'input 2Bl', 'input 2Ar'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [4, 3]);
% gui.addControl(ParameterSwitchButton('Xsit FD', ...
%   {'input 1Fl', 'input 1Dr', 'input 2Fl', 'input 2Dr'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [5, 3]);
% gui.addControl(ParameterSwitchButton('Xsit EF', ...
%   {'input 1El', 'input 1Fr', 'input 2El', 'input 2Fr'}, ...
%   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%   zeros(1, 4), vstrength * ones(1, 4), [], false), [6, 3]);


% % gui.addControl(ParameterSwitchButton('Xsit AD', ...
% %   {'input 1Al', 'input 1Dr', 'input 2Al', 'input 2Dr'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [1, 2]);
% % gui.addControl(ParameterSwitchButton('Xsit AF', ...
% %   {'input 1Al', 'input 1Fr', 'input 2Al', 'input 2Fr'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [2, 2]);
% % gui.addControl(ParameterSwitchButton('Xsit AE', ...
% %   {'input 1Al', 'input 1Er', 'input 2Al', 'input 2Er'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [3, 2]);
% % gui.addControl(ParameterSwitchButton('Xsit AB', ...
% %   {'input 1Al', 'input 1Br', 'input 2Al', 'input 2Br'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [4, 2]);
% % gui.addControl(ParameterSwitchButton('Xsit BE', ...
% %   {'input 1Bl', 'input 1Er', 'input 2Bl', 'input 2Er'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [5, 2]);
% % gui.addControl(ParameterSwitchButton('Xsit DB', ...
% %   {'input 1Br', 'input 1Dl', 'input 2Br', 'input 2Dl'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [6, 2]);

%gui.addControl(ParameterSwitchButton('Xsit CB', ...
%  {'input 1Cl', 'input 1Br', 'input 2Cl', 'input 2Br'}, ...
%  {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%  zeros(1, 4), vstrength * ones(1, 4), [], false), [1, 3]);
%gui.addControl(ParameterSwitchButton('Xsit CE', ...
%  {'input 1Cl', 'input 1Er', 'input 2Cl', 'input 2Er'}, ...
%  {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%  zeros(1, 4), vstrength * ones(1, 4), [], false), [2, 3]);
%gui.addControl(ParameterSwitchButton('Xsit CF', ...
%  {'input 1Cl', 'input 1Fr', 'input 2Cl', 'input 2Fr'}, ...
%  {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%  zeros(1, 4), vstrength * ones(1, 4), [], false), [3, 3]);
%gui.addControl(ParameterSwitchButton('Xsit CD', ...
%  {'input 1Cl', 'input 1Dr', 'input 2Cl', 'input 2Dr'}, ...
%  {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%  zeros(1, 4), vstrength * ones(1, 4), [], false), [4, 3]);
%gui.addControl(ParameterSwitchButton('Xsit FD', ...
%  {'input 1Fl', 'input 1Dr', 'input 2Fl', 'input 2Dr'}, ...
%  {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%  zeros(1, 4), vstrength * ones(1, 4), [], false), [5, 3]);
%gui.addControl(ParameterSwitchButton('Xsit EF', ...
%  {'input 1El', 'input 1Fr', 'input 2El', 'input 2Fr'}, ...
%  {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
%  zeros(1, 4), vstrength * ones(1, 4), [], false), [6, 3]);

% % gui.addControl(ParameterSwitchButton('"regli A"', 'inputRegli', 'amplitude', 0, wstrength), [1,3]);
% % gui.addControl(ParameterSwitchButton('"manu B"', 'inputManu', 'amplitude', 0, wstrength), [2,3]);
% % gui.addControl(ParameterSwitchButton('"gasser C"', 'inputGasser', 'amplitude', 0, wstrength), [3,3]);
% % gui.addControl(ParameterSwitchButton('"bosa D"', 'inputBosa', 'amplitude', 0, wstrength), [4,3]);
% % gui.addControl(ParameterSwitchButton('"colat E"', 'inputColat', 'amplitude', 0, wstrength), [5,3]);
% % gui.addControl(ParameterSwitchButton('"kaki F"', 'inputKaki', 'amplitude', 0, wstrength), [6,3]);


% % %gui.addControl(ParameterSlider('atn_sr', 'boost atn_sr', 'amplitude', [-5, 5], '%0.1f', 1, 'boost atn_sr'), [1, 3]);
% % gui.addControl(ParameterSlider('hconfB', {'inputCONF1B','inputCONF2B'}, {'amplitude','amplitude'}, [0, 2], '%0.1f', 1), [1, 4]);
% % gui.addControl(ParameterSlider('hconfE', {'inputCONF1E','inputCONF2E'}, {'amplitude','amplitude'}, [0, 2], '%0.1f', 1), [2, 4]);
% % gui.addControl(ParameterSlider('hwmfB', {'inputWMF1B','inputWMF2B'}, {'amplitude','amplitude'}, [0, 2], '%0.1f', 1), [3, 4]);
% % gui.addControl(ParameterSlider('hwmfE', {'inputWMF1E','inputWMF2E'}, {'amplitude','amplitude'}, [0, 2], '%0.1f', 1), [4, 4]);
% % gui.addControl(ParameterSwitchButton('Target BE', ...
% %   {'input 1Bl', 'input 1Er', 'input 2Bl', 'input 2Er'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [5, 4]);
% % gui.addControl(ParameterSwitchButton('Target B-Dog', ...
% %   {'input 1Bl', 'input 1Dogr', 'input 2Bl', 'input 2Dogr'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 4), vstrength * ones(1, 4), [], false), [6, 4]);
% % 
% % 
% % gui.addControl(ParameterSwitchButton('Target B-E-Dog', ...
% %   {'input 1Bl', 'input 1Em', 'input 1Dogr', 'input 2Bl', 'input 2Em', 'input 2Dogr'}, ...
% %   {'amplitude', 'amplitude', 'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% %   zeros(1, 6), vstrength * ones(1, 6), [], false), [2, 5]);
% % % gui.addControl(ParameterSwitchButton('Known Words', ...
% % %     {'inputCup', 'inputBall', 'inputCat', 'inputDog', 'inputBottle', 'inputBook', 'inputCar'}, ...
% % %     {'amplitude', 'amplitude', 'amplitude', 'amplitude', 'amplitude', 'amplitude', 'amplitude'}, ...
% % %     zeros(1,7), wstrength*ones(1,7)), [2,5]);
% % gui.addControl(ParameterSwitchButton('"Dog"', 'inputDog', 'amplitude', 0, wstrength), [3,5]);
% % gui.addControl(ParameterSwitchButton('Dax Object', ...
% %   {'input 1Bm', 'input 2Bm'}, ...
% %   {'amplitude', 'amplitude'}, zeros(1, 2), vstrength * ones(1, 2), [], false), [4, 5]);
% % %gui.addControl(ParameterSwitchButton('Flush WM', {'wm_c1', 'wm_c2', 'wm_s', 'wm_f1', 'wm_f2'}, ...
% % %    {'h', 'h', 'h', 'h', 'h'}, ones(1,5)*-5, ones(1,5)*-15, [], false), [4, 5]);
% % %gui.addControl(ParameterSwitchButton('Hebbian fast/slow', {'hatn_c1', 'hatn_c2'}, ...
% % %    {'tauBuild', 'tauBuild'}, [500,500], [50,50], [], false), [3, 5]);

% general control buttons
gui.addVisualization(TimeDisplay(), [1, 5], [1, 1], 'control');
gui.addControl(GlobalControlButton('Pause', gui, 'pauseSimulation', true, false, false, 'pause simulation'), [1, 6]);
gui.addControl(GlobalControlButton('Reset', gui, 'resetSimulation', true, false, true, 'reset simulation'), [2, 6]);
gui.addControl(GlobalControlButton('Parameters', gui, 'paramPanelRequest', true, false, false, 'open parameter panel'), [3, 6]);
gui.addControl(GlobalControlButton('Save', gui, 'saveParameters', true, false, true, 'save parameter settings'), [4, 6]);
gui.addControl(GlobalControlButton('Load', gui, 'loadParameters', true, false, true, 'load parameter settings'), [5, 6]);
gui.addControl(GlobalControlButton('Quit', gui, 'quitSimulation', true, false, false, 'quit simulation'), [6, 6]);

