#SBATCH --job-name=matlab-WOLVES_job  # Set job name
#SBATCH -o matlab-WOLVES-%j.out  # Write job output to MatJob-(job_number).out
#SBATCH -e matlab-WOLVES-%j.err  # Write job error to MatJob-(job_number).err
#SBATCH -p ib-24-96
#SBATCH --qos=ib
#SBATCH --time="96:00:00"
#SBATCH --mem=40GB
#set up environment
module add matlab/2020a
#run the application
matlab -nodisplay -nosplash -singleCompThread -r XSIT_Manual_run
  
