%% create gui and visualizations

% create GUI object;
gui = StandardGUI(sim, [25, 75, 1800, 1000], 0, [0, 0.175, 1.0, 0.8], [8, 21], [0.015, 0.0225], [0, 0, 1.0, 0.15], [6, 6], ...
  elementGroups, elementsInGroup);

gui.addVisualization(MultiPlot({'history lookL','history lookLWB', 'history lookC', 'history lookRWB','history lookR'}, {'output', 'output', 'output', 'output', 'output'}, ...
  [1, 1, 1, 1, 1], 'horizontal', ...
  {'XLim', [-historyDuration, 10], 'YLim', [-1.5, 1.5], 'Box', 'on', 'XGrid', 'on', 'YGrid', 'on'}, ...
  {{'r-', 'LineWidth', 2, 'XData', 0:-1:-historyDuration+1}, ...
  {'r-.', 'LineWidth', 2, 'XData', 0:-1:-historyDuration+1}, ...
  {'g-.', 'LineWidth', 2, 'XData', 0:-1:-historyDuration+1}, ...
  {'b-.', 'LineWidth', 2, 'XData', 0:-1:-historyDuration+1}, ...
  {'b-', 'LineWidth', 2, 'XData', 0:-1:-historyDuration+1}}, ...
  'looking time'), [1, 16], [2,3]);
gui.addVisualization(MultiPlot({'word', 'word'}, {'activation', 'output'}, [1, 10], 'horizontal', ...
  {'XLim', [1, fieldSize_wd], 'YLim', [-15, 15], 'Box', 'on'}, {{'Color', 'b'}, {'Color', 'r'}}, 'word'), ...
  [1, 4], [1, 3]);


gui.addVisualization(MultiPlot({'hword'}, {'output'}, [1], 'horizontal', ...
    {'XLim', [1, fieldSize_wd], 'YLim', [0, 1], 'Box', 'on'}, {{'b', 'LineWidth', 1}}, ...
  'hebbian word'), [2, 4], [1, 3] );

%commented to be replaced by hwm_f below % % gui.addVisualization(MultiPlot({'hwm_s'}, {'output'}, [1], 'horizontal', ...
% % %   {'XLim', [1, fieldSize_spt], 'YLim', [0, 1], 'Box', 'on'}, {{'b', 'LineWidth', 1}}, 'hwm s'), ...
% % %   [2, 7], [1, 3]);

gui.addVisualization(MultiPlot({['hwm_f' num2str(1)]}, {'output'}, [1], 'horizontal', ...
  {'XLim', [1, fieldSize_ftr], 'YLim', [0, 1], 'Box', 'on'}, {{'b', 'LineWidth', 1}}, 'hwm f'), ...
  [2, 7], [1, 3]);
gui.addVisualization(MultiPlot({'wm_s', 'wm_s'}, {'activation', 'output'}, [1, 10], 'horizontal', ...
  {'XLim', [1, fieldSize_spt], 'YLim', [-15, 15], 'Box', 'on'}, {{'Color', 'b'}, {'Color', 'r'}}, 'wm s'), ...
  [2, 10], [1, 3]);


gui.addVisualization(MultiPlot({'atn_sa', 'atn_sa'}, {'activation', 'output'}, [1, 10], 'horizontal', ...
  {'XLim', [1, fieldSize_spt], 'YLim', [-15, 15], 'Box', 'on'}, {{'Color', 'b'}, {'Color', 'r'}}, 'atn sa'), ...
  [2, 13], [1, 3]);
gui.addVisualization(MultiPlot({'con_s', 'con_s'}, {'activation', 'output'}, [1, 10], 'horizontal', ...
  {'XLim', [1, fieldSize_spt], 'YLim', [-15, 15], 'Box', 'on'}, {{'Color', 'b'}, {'Color', 'r'}}, 'con s'), ...
  [1, 10], [1, 3]);
% gui.addVisualization(MultiPlot({'hcon_s'}, {'output'}, [1], 'horizontal', ...
%   {'XLim', [1, fieldSize_spt], 'YLim', [0, 1], 'Box', 'on'}, {{'b', 'LineWidth', 1}}, 'hcon s'), ...
%   [1, 7], [1, 3]);
gui.addVisualization(MultiPlot({['hcon_f' num2str(1)]}, {'output'}, [1], 'horizontal', ...
  {'XLim', [1, fieldSize_ftr], 'YLim', [0, 1], 'Box', 'on'}, {{'b', 'LineWidth', 1}}, 'hcon f'), ...
  [1, 7], [1, 3]);

% gui.addVisualization(MultiPlot({'motor', 'motor', 'mrn', 'mrn', 'cos_m', 'cos_m'}, ...
%   {'activation', 'output', 'activation', 'output', 'activation', 'output'}, ...
%   [1, 10, 1, 10, 1, 10], 'horizontal', ...
%   {'XLim', [1, fieldSize_spt], 'YLim', [-15, 15], 'Box', 'on'}, ...
%   {{'Color', 'b'}, {'Color', 'r'}, ...
%   {'bs', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 5}, ...
%   {'rs', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 5}, ...
%   {'bo', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 10}, ...
%   {'ro', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 10}}, ...
%   'motor'), [1, 13], [1, 3]);

gui.addVisualization(MultiPlot({'atn_sr', 'atn_sr'}, {'activation', 'output'}, [1, 10], 'horizontal', ...
  {'XLim', [1, fieldSize_spt], 'YLim', [-15, 15], 'Box', 'on'}, {{'Color', 'b'}, {'Color', 'r'}},  'atn sr'), ...
  [2, 19], [1, 3]);
gui.addVisualization(MultiPlot({'ior_s', 'ior_s', 'pd_c1', 'pd_c1', 'pd_c2', 'pd_c2', 'cos', 'cos'}, ...
  {'activation', 'output', 'activation', 'output', 'activation', 'output', 'activation', 'output'}, ...
  [1, 10, 1, 10, 1, 10, 1, 10], 'horizontal', ...
  {'XLim', [1, fieldSize_spt], 'YLim', [-15, 15], 'Box', 'on'}, ...
  {{'Color', 'b'}, {'Color', 'r'}, ...
  {'bs', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 1}, ...
  {'rs', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 1}, ...
  {'bs', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 5}, ...
  {'rs', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 5}, ...
  {'bo', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 10}, ...
  {'ro', 'MarkerSize', 4, 'XDataMode', 'manual', 'XData', 10}}, ...
  'ior s'), [1, 19], [1, 3]);


for i = 1 : nFeatures
  n = num2str(i);
  if i == nFeatures % x-axis labels only for the bottommost axes
    xla = 'space (allo)';
    xlr = 'space (retn)';
    xlw = 'word label';
  else
    xla = [];
    xlr = [];
    xlw = [];
  end
  ov = 3*i; % vertical offset for placing visualizations of the current feature
  
  gui.addVisualization(ScaledImage(['wf' n], 'activation', [-7.5, 7.5], ...
    {'CLim', [-7.5, 7.5], 'YAxisLocation', 'right', 'YDir', 'normal'}, {}, ['word feature' n], xlw), [ov, 4], [3, 3]);
  gui.addVisualization(ScaledImage(['wm_c' n], 'activation', [-7.5, 7.5], ...
    {'CLim', [-7.5, 7.5], 'YAxisLocation', 'right', 'YDir', 'normal'}, {}, ['scene wm' n], xla), [ov, 10], [3, 3]);
  gui.addVisualization(ScaledImage(['hwm_c' n], 'output', [0, 1.0], ...
    {'CLim', [0,1.0], 'YAxisLocation', 'right', 'YDir', 'normal'}, {}, ['hebbian scene' n], xla), [ov, 7], [3, 3]);
  gui.addVisualization(ScaledImage(['hwf' n], 'output', [0, 1.0], ...
    {'CLim', [0,1.0], 'YAxisLocation', 'right', 'YDir', 'normal'}, {}, ['hebbian word' n], xlw), [ov, 1], [3, 3]);
  gui.addVisualization(ScaledImage(['atn_c' n], 'activation', [-7.5, 7.5], ...
    {'CLim', [-7.5, 7.5], 'YAxisLocation', 'right', 'YDir', 'normal'}, {}, ['scene atn' n], xla), [ov, 13], [3, 3]);
  gui.addVisualization(MultiPlot({['wm_f' n], ['wm_f' n]}, {'activation', 'output'}, [1, 10], 'vertical', ...
    {'YLim', [1, fieldSize_ftr], 'XLim', [-15, 15], 'XDir', 'reverse', 'YAxisLocation', 'right', 'Box', 'on'}, ...
    {{'Color', 'b'}, {'Color', 'r'}}, ['wm f' n]), [ov, 16], [3, 1]);
  gui.addVisualization(MultiPlot({['con_f' n], ['con_f' n]}, {'activation', 'output'}, [1, 10], 'vertical', ...
    {'YLim', [1, fieldSize_ftr], 'XLim', [-15, 15], 'XDir', 'reverse', 'YAxisLocation', 'right', 'Box', 'on'}, ...
    {{'Color', 'b'}, {'Color', 'r'}}, ['con f' n]), [ov, 17], [3, 1]);
  gui.addVisualization(MultiPlot({['atn_f' n], ['atn_f' n]}, {'activation', 'output'}, [1, 10], 'vertical', ...
    {'YLim', [1, fieldSize_ftr], 'XLim', [-15, 15], 'XDir', 'reverse', 'YAxisLocation', 'right', 'Box', 'on'}, ...
    {{'Color', 'b'}, {'Color', 'r'}}, ['atn f' n]), [ov, 18], [3, 1]);
  
  gui.addVisualization(ScaledImage(['vis_f' n], 'activation', [-7.5, 7.5], ...
    {'CLim', [-7.5, 7.5], 'YAxisLocation', 'right', 'YDir', 'normal'}, {}, ['ret f' n], xlr, ['feature ' n]), ...
    [ov, 19], [3, 3]);
end