gui = StandardGUI(sim, [50, 50, 900, 750], 0, [0.05, 0.1, 0.9, 0.9], [3, 1], ...
    [0.02, 0.05], [0.0, 0.0, 1.0, .1], [1, 6], elementGroups, elementsInGroup);
% %     0.06, [0.0, 0.0, 1.0, 1/4], [1.8, 6], ...

halfSize = spatialHalfSize;
gui.addVisualization(MultiPlot({'input_v'}, {'output'}, ...
    1, 'horizontal', {'YLim', [-15, 15], 'XLim', [-halfSize, halfSize], 'XGrid', 'on', 'YGrid', 'on'}, ...
    {{'b', 'LineWidth', 3, 'XDataMode', 'manual', 'XData', (-halfSize:halfSize)}}, ...
    'stimulus', 'space', 'input'), [1, 1]);

gui.addVisualization(MultiPlot({'field a', 'field a', 'g', 'g', 'x', 'x'}, {'activation', 'output', 'activation', 'output', 'activation', 'output'}, ...
  [1, 10, 1, 10, 1, 10], 'horizontal', {'YLim', [-15, 15], 'XLim', [-halfSize, halfSize], 'XGrid', 'on', 'YGrid', 'on'}, ...
  {{'b', 'LineWidth', 3, 'XDataMode', 'manual', 'XData', (-halfSize:halfSize)}, ...
  {'r', 'LineWidth', 2, 'XDataMode', 'manual', 'XData', (-halfSize:halfSize)}, ...
  {'bv', 'MarkerSize', 8, 'XDataMode', 'manual', 'XData', 0}, ...
  {'rv', 'MarkerSize', 8, 'XDataMode', 'manual', 'XData', 0}, ...
  {'bs', 'MarkerSize', 8, 'XDataMode', 'manual', 'XData', 0}, ...
  {'rs', 'MarkerSize', 8, 'XDataMode', 'manual', 'XData', 0}}, ...
  'field a', 'space', 'activation / output'), [2, 1]);

gui.addVisualization(MultiPlot({'field s', 'field s','r', 'r'}, {'activation', 'output', 'activation', 'output'}, ...
    [1, 10, 1, 10], 'horizontal', {'YLim', [-25, 25], 'XLim', [-halfSize, halfSize], 'XGrid', 'on', 'YGrid', 'on'}, ...
    {{'b', 'LineWidth', 3, 'XDataMode', 'manual', 'XData', (-halfSize:halfSize)}, ...
    {'r', 'LineWidth', 2, 'XDataMode', 'manual', 'XData', (-halfSize:halfSize)}, ...
    {'bs', 'MarkerSize', 8, 'XDataMode', 'manual', 'XData', 0}, ...
    {'rs', 'MarkerSize', 8, 'XDataMode', 'manual', 'XData', 0}}, ...
    'field s', 'space', 'activation / output'), [3, 1]);

gui.addControl(GlobalControlButton('Pause', gui, 'pauseSimulation', true, false, false, 'pause simulation'), [1, 1.5]);
gui.addControl(GlobalControlButton('Parameters', gui, 'paramPanelRequest', true, false, false, 'open parameter panel'), [1, 2.5]);
gui.addControl(GlobalControlButton('Save', gui, 'saveParameters', true, false, true, 'save parameter settings'), [1, 3.5]);
gui.addControl(GlobalControlButton('Load', gui, 'loadParameters', true, false, true, 'load parameter settings'), [1, 4.5]);
gui.addControl(GlobalControlButton('Quit', gui, 'quitSimulation', true, false, false, 'quit simulation'), [1, 5.5]);
