%% setting up the GUI
elementGroups = sim.elementLabels;
elementsInGroup = sim.elementLabels;
% elementGroups = {'field u', 'field v', 'field w', 'field atn', 'field vis', 'u -> u', 'u -> v', 'u -> w', 'u -> atn', 'u -> vis' ...
%   'v -> u (local)', 'v -> u (global)', 'v -> w (local)', 'v -> w (global)', ...
%   'w -> u', 'w -> v', 'w -> w', 'w -> atn', 'w -> vis', 'atn -> u', 'atn -> w', 'atn -> atn', 'atn -> vis', ...
%   'vis -> u', 'vis -> w', 'vis -> atn', 'vis -> vis (exh)', 'vis -> vis (inh)', 'vis -> vis (global)', ...
%   'vis stim 1', 'vis stim 2', 'vis stim 3', 'flat boost', 'scale flat boost', 'scale flat boost 2', 'scale flat boost 3', 'wheel pattern', 'wheel stimulus', 'wheel noise', 'noise kernel u', 'noise kernel v', 'noise kernel w', 'noise kernel atn', 'noise kernel vis'};


figureWidth = 1200;
figureHeight = 600;

gui = StandardGUI(sim, [50, 250, figureWidth, figureHeight], 0.05, [0.05, .1, .95, .9], [1, 7], [0.02, 0.05], [0.0, 0.0, 1.0, .05], [1, 6], ...
  elementGroups, elementGroups);

% % % gui = StandardGUI(sim, [50, 250, 1200, 500], 0.05, [0.0, .05, 1, .95], [1, 7], [0.02, 0.05], [0.0, 0.0, 1.0, .05], [1, 6], ...
% % %   elementGroups, elementGroups);

gui.addVisualization(MultiPlot({'field atn', 'field atn'}, {'activation', 'output'}, ...
  [1, 10], 'vertical', {'XLim', [-25, 25], 'YLim', [1,361], 'XGrid', 'on', 'YGrid', 'on'}, ...
  {{'b', 'LineWidth', 3}, {'r', 'LineWidth', 2}}, ...
  'field atn'), [1, 4]);
gui.addVisualization(MultiPlot({'field u', 'field u'}, {'activation', 'output'}, ...
  [1, 10], 'vertical', {'XLim', [-50, 55], 'YLim', [1,361], 'XGrid', 'on', 'YGrid', 'on'}, ...
  {{'b', 'LineWidth', 3}, {'r', 'LineWidth', 2}}, ...
  'field u'), [1, 3]);
gui.addVisualization(MultiPlot({'field v', 'field v'}, {'activation', 'output'}, ...
  [1, 10], 'vertical', {'XLim', [-25, 25], 'YLim', [1,361], 'XGrid', 'on', 'YGrid', 'on'}, ...
  {{'b', 'LineWidth', 3}, {'r', 'LineWidth', 2}}, ...
  'field v'), [1, 2]);
gui.addVisualization(MultiPlot({'field w', 'field w'}, {'activation', 'output'}, ...
  [1, 10], 'vertical', {'XLim', [-25, 25], 'YLim', [1,361], 'XGrid', 'on', 'YGrid', 'on'}, ...
  {{'b', 'LineWidth', 3}, {'r', 'LineWidth', 2}}, ...
  'field w'), [1, 1]);

gui.addVisualization(ScaledImage('field vis', 'activation', [-7.5, 7.5], ...
    {'CLim', [-7.5, 7.5], 'YLim', [1,361], 'YAxisLocation', 'left', 'YDir', 'normal'}, {}, 'field vis', 'space', 'feature'), [1, 5], [1, 3]);

% general control buttons
gui.addControl(GlobalControlButton('Pause', gui, 'pauseSimulation', true, false, false, 'pause simulation'), [1, 1.5]);
%gui.addControl(GlobalControlButton('Reset', gui, 'resetSimulation', true, false, true, 'reset simulation'), [1, 2]);
gui.addControl(GlobalControlButton('Parameters', gui, 'paramPanelRequest', true, false, false, 'open parameter panel'), [1, 2.5]);
gui.addControl(GlobalControlButton('Save', gui, 'saveParameters', true, false, true, 'save parameter settings'), [1, 3.5]);
gui.addControl(GlobalControlButton('Load', gui, 'loadParameters', true, false, true, 'load parameter settings'), [1, 4.5]);
gui.addControl(GlobalControlButton('Quit', gui, 'quitSimulation', true, false, false, 'quit simulation'), [1, 5.5]);
